/*
* various queries to sanity check the GBS keyfile database 
*/
/* report fastq link counts by flowcell , platename, lane */
select 
   fastq_link,
   Flowcell,
   PlateName,
   lane,
   count(*) 
from
   gbsKeyFileFact
group by 
   fastq_link,
   Flowcell,
   PlateName,
   lane;

   
   


select
    *
from
    gbsKeyFileFact
where
    Flowcell = 'C6JT3ANXX' and
    PlateName = 'SQ0032' and
    length(rtrim(ltrim(coalesce(Fastq_link,'')))) = 0;

update gbsKeyFileFact
    set Fastq_link = '/dataset/hiseq/active/fastq-link-farm/SQ0032_C6JT3ANXX_s_8_fastq.txt.gz'
where
    Flowcell = 'C6JT3ANXX' and
    PlateName = 'SQ0032' and
    length(rtrim(ltrim(coalesce(Fastq_link,'')))) = 0;

   
