/*
* this script extracts a custom keyfile   
* example of doing this manually : 
head -n 1 /dataset/hiseq/active/key-files/SQ0112.txt > key.txt
grep -f bulls /dataset/hiseq/active/key-files/SQ0006.txt >> key.txt
grep Cattle /dataset/hiseq/active/key-files/SQ*.txt | grep Lawson | grep PstI | awk -F ".txt:" '{print $2}' >> key.txt
*/
\a
\f '\t'
\pset footer off
\o custom_example.txt
select 
   Flowcell,
   Lane,
   Barcode,
   Sample,
   PlateName,
   PlateRow as Row,
   PlateColumn as Column,
   LibraryPrepID,
   Counter,
   Comment,
   Enzyme,
   Species,
   NumberOfBarcodes,
   Bifo,
   Fastq_link
from 
   biosampleob s join gbsKeyFileFact g on 
   g.biosampleob = s.obid
where 
   lower(g.species) like '%bulls%' or 
   ( 
     lower(g.species) like '%deer%' and
     g.enzyme = 'PstI' and 
     lower(g.comment) like '%stuart%' 
   )
order by 
   factid;
